services:
  - type: web
    name: ros2-wiki
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --host=0.0.0.0 --port=$PORT --workers=1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///ros2_wiki.db
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
      - key: ADMIN_EMAIL
        value: admin@ros2wiki.com
      - key: FLASK_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: ros2-wiki
          envVarKey: PORT

databases:
