services:
  - type: web
    name: ros2-wiki
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --host=0.0.0.0 --port=$PORT --workers=2
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ros2-wiki-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: MIN_PASSWORD_LENGTH
        value: "8"
      - key: REQUIRE_SPECIAL_CHARS
        value: "True"

databases:
  - name: ros2-wiki-db
    databaseName: ros2_wiki
    user: ros2_wiki_user
    region: oregon
