services:
  - type: web
    name: ros2-wiki-enterprise
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements_render.txt
      python cloud_init_db.py
    startCommand: gunicorn app_render:app --bind=0.0.0.0:$PORT --workers=2 --timeout=60
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: SECRET_KEY
        value: "3092b9fbcd9523417c2871c8d3b5410cca586856627bc323f4054c5f8f4297f4"
      - key: DATABASE_URL
        fromDatabase:
          name: ros2-wiki-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: MIN_PASSWORD_LENGTH
        value: "12"
      - key: REQUIRE_SPECIAL_CHARS
        value: "True"
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_EMAIL
        value: "seventee_0611@qq.com"
      - key: ADMIN_PASSWORD
        value: "IlukRJovZ05Tyx$b"
      - key: AUTO_CREATE_ADMIN
        value: "true"
      - key: CSRF_ENABLED
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"

databases:
  - name: ros2-wiki-db
    databaseName: ros2_wiki
    user: ros2_wiki_user
    region: oregon
    plan: free