services:
  - type: web
    name: ros2-wiki-enterprise
    env: python
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python database_optimization.py
    startCommand: gunicorn app_secured:app --host=0.0.0.0 --port=$PORT --workers=4 --timeout=60
    envVars:
      - key: SECRET_KEY
        value: "3092b9fbcd9523417c2871c8d3b5410cca586856627bc323f4054c5f8f4297f4"
      - key: DATABASE_URL
        fromDatabase:
          name: ros2-wiki-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: MIN_PASSWORD_LENGTH
        value: "12"
      - key: REQUIRE_SPECIAL_CHARS
        value: "True"
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_EMAIL
        value: "seventee_0611@qq.com"
      - key: ADMIN_PASSWORD
        value: "IlukRJovZ05Tyx$b"
      - key: AUTO_CREATE_ADMIN
        value: "true"
      - key: CSRF_ENABLED
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"

databases:
  - name: ros2-wiki-db
    databaseName: ros2_wiki
    user: ros2_wiki_user
    region: oregon
