services:
  - type: web
    name: ros2-wiki
    env: python
    region: oregon
    buildCommand: echo "No dependencies needed - using Python stdlib only"
    startCommand: python enhanced_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        fromService:
          type: web
          name: ros2-wiki
          envVarKey: PORT

databases:
